#pragma once
#include <myl/version.hpp>

#define MYTHOS_VERSION_MAJOR 0
#define MYTHOS_VERSION_MINOR 0
#define MYTHOS_VERSION_PATCH 0
#define MYTHOS_VERSION MYL_MAKE_VERSION(MYTHOS_VERSION_MAJOR, MYTHOS_VERSION_MINOR, MYTHOS_VERSION_PATCH)
#define MYTHOS_VERSION_STRING MYL_MAKE_VERSION_STRING(MYTHOS_VERSION_MAJOR, MYTHOS_VERSION_MINOR, MYTHOS_VERSION_PATCH)
