#pragma once
#include <myl/definitions.hpp>

namespace myth {
    using keycode = myl::u16;
    namespace key {
        enum : keycode {
            escape,
            enter,
            tab,
            backspace,

            a,
            b,
            c,
            d,
            e,
            f,
            g,
            h,
            i,
            j,
            k,
            l,
            m,
            n,
            o,
            p,
            q,
            r,
            s,
            t,
            u,
            v,
            w,
            x,
            y,
            z,

            n0,
            n1,
            n2,
            n3,
            n4,
            n5,
            n6,
            n7,
            n8,
            n9,

            kp0,
            kp1,
            kp2,
            kp3,
            kp4,
            kp5,
            kp6,
            kp7,
            kp8,
            kp9,
            kp_add,
            kp_subtract,
            kp_multiply,
            kp_divide,
            kp_decimal,
            kp_equals,
            kp_enter,

            space,
            equals,
            dash,
            comma,
            period,
            slash,
            backslash,
            semicolon,
            apostrophe,
            grave_accent,
            left_bracket,
            right_bracket,

            up,
            down,
            left,
            right,

            caps_lock,
            num_lock,
            scroll_lock,

            left_shift,
            left_control,
            left_alt,
            left_super,
            right_shift,
            right_control,
            right_alt,
            right_super,

            home,
            end,
            page_up,
            page_down,
            insert,
            delete_key,
            pause,
            printscreen,

            f1,
            f2,
            f3,
            f4,
            f5,
            f6,
            f7,
            f8,
            f9,
            f10,
            f11,
            f12,
            f13,
            f14,
            f15,
            f16,
            f17,
            f18,
            f19,
            f20,
            f21,
            f22,
            f23,
            f24,

            size,
            unknown
        };
    }
}
