set(MYTHOS_DEFINITIONS)

# Build Type Definition
if (CMAKE_BUILD_TYPE STREQUAL "Debug")
    list(APPEND MYTHOS_DEFINITIONS MYTHOS_BUILD_DEBUG)
elseif(CMAKE_BUILD_TYPE STREQUAL "Release")
    list(APPEND MYTHOS_DEFINITIONS MYTHOS_BUILD_RELEASE)
elseif(CMAKE_BUILD_TYPE STREQUAL "RelWithDebInfo")
    list(APPEND MYTHOS_DEFINITIONS MYTHOS_BUILD_DEV_RELEASE)
elseif(CMAKE_BUILD_TYPE STREQUAL "MinSizeRel")
    list(APPEND MYTHOS_DEFINITIONS MYTHOS_BUILD_TINY)
else() # Default is release
    list(APPEND MYTHOS_DEFINITIONS MYTHOS_BUILD_RELEASE)
endif()